apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: autoscalingpolicies.cerebral.containership.io
spec:
  group: cerebral.containership.io
  names:
    kind: AutoscalingPolicy
    listKind: AutoscalingPolicyList
    singular: autoscalingpolicy
    plural: autoscalingpolicies
    shortNames:
    - asp
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - metricsBackend
            - metric
            - scalingPolicy
            - pollInterval
            - samplePeriod
          properties:
            metricsBackend:
              type: string
            metric:
              type: string
            metricConfiguration:
              type: object
            scalingPolicy:
              type: object
              properties:
                scaleUp:
                  type: object
                  properties:
                    threshold:
                      type: number
                      format: float
                    comparisonOperator:
                      type: string
                      enum: [ ">", "<", ">=", "<=", "==", "!=" ]
                    adjustmentType:
                      type: string
                      enum: [ "absolute", "percent" ]
                    adjustmentValue:
                      type: integer
                      minimum: 0
                scaleDown:
                  type: object
                  properties:
                    threshold:
                      type: number
                      format: float
                    comparisonOperator:
                      type: string
                      enum: [ ">", "<", ">=", "<=", "==", "!=" ]
                    adjustmentType:
                      type: string
                      enum: [ "absolute", "percent" ]
                    adjustmentValue:
                      type: integer
                      minimum: 0
            pollInterval:
              type: integer
              minimum: 0
            samplePeriod:
              type: integer
              minimum: 0
