apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: autoscalinggroups.cerebral.containership.io
spec:
  group: cerebral.containership.io
  version: v1alpha1
  names:
    kind: AutoscalingGroup
    listKind: AutoscalingGroupList
    singular: autoscalinggroup
    plural: autoscalinggroups
    shortNames:
    - ag
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - engine
          - minNodes
          - maxNodes
          - cooldownPeriod
          properties:
            nodeAffinity:
              type: object
            policies:
              type: array
              items:
                type: string
            engine:
              type: string
            suspended:
              type: boolean
            cooldownPeriod:
              type: integer
            maxNodes:
              type: integer
              minimum: 0
            minNodes:
              type: integer
              minimum: 0
            scalingStrategy:
              type: object
              properties:
                up:
                  type: string
                down:
                  type: string
        status:
          properties:
            lastUpdatedAt:
              type: integer
